# -*- coding: utf-8 -*-
"""
Script para actualizar e integrar completamente los concejales de Medellín (renuncias de Sebastián López y Claudia Carrasquilla + posesión de Milton Vasco y Jorge Julián Osorio) y las bancadas de concejales de los demás municipios del Valle de Aburrá y Rionegro en src/data/politicalHouses/politicalHousesMasterData.ts
"""
import sys

NODES_REPLACEMENT = """  // ==========================================
  // CONCEJALES Y AGENTES MUNICIPALES POR PARTIDO (PA-009 EXTENDIDO)
  // ==========================================
  
  // --- CONCEJALES CENTRO DEMOCRÁTICO (MEDELLÍN Y SUBREGIONES) ---
  {
    id: 'actor-cd-concejal-claudia-carrasquilla',
    name: 'Claudia Carrasquilla Minami',
    alias: 'La Fiscal de Hierro',
    role: 'concejal',
    roleLabel: 'Exconcejal de Medellín (Renunció 2026) / Viceministra de Defensa',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'extramunicipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 14966,
    cedula: '43.497.054',
    status: 'Renunció al Concejo (Agosto 2026) - Viceministra de Defensa Nacional',
    bio: 'Abogada penalista y exfiscal nacional contra el crimen organizado. Elegida concejal con 14.966 votos. Renunció a su curul en agosto de 2026 tras ser designada Viceministra de Defensa Nacional para coordinar las políticas de seguridad ciudadana y convivencia en el Gobierno. Su curul en el Concejo de Medellín fue asumida por el médico y exrector del CES, Jorge Julián Osorio Gómez.',
    extramunicipalConnection: 'Ministerio de Defensa Nacional, Fuerzas Militares, cúpula judicial y bancada nacional del Centro Democrático.',
    municipalAnchor: 'Concejo de Medellín (2024-2026), comisiones de seguridad y justicia.',
    socialProfiles: {
      xTwitter: '@FiscalHierro',
      instagram: '@claudiacarrasquillam',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Claudia Carrasquilla renuncia al Concejo de Medellín para asumir como Viceministra de Defensa',
        source: 'El Colombiano',
        year: 2026,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-milton-vasco',
    name: 'Milton Darío Vasco Restrepo',
    alias: 'Milton Vasco',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín en funciones (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 6120,
    status: 'En funciones (Asumió curul en mayo 2026 en reemplazo de Sebastián López)',
    bio: 'Administrador y dirigente uribista con trayectoria en la administración pública distrital. Exdirector general de Metroparques. Asumió la curul del Centro Democrático en el Concejo de Medellín en mayo de 2026 luego de que Sebastián López renunciara formalmente para coordinar la campaña presidencial de Paloma Valencia.',
    extramunicipalConnection: 'Vínculo directo con el Directorio Departamental y la Dirección Nacional del Centro Democrático.',
    municipalAnchor: 'Concejo de Medellín, Comisión Primera del Plan y Comisión de Presupuesto.',
    socialProfiles: {
      xTwitter: '@MiltonVascoR',
      verifiedOfficial: false
    },
    newsLinks: [
      {
        title: 'Milton Vasco se posesiona como nuevo concejal de Medellín por el Centro Democrático',
        source: 'Telemedellín',
        year: 2026,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-jorge-osorio',
    name: 'Jorge Julián Osorio Gómez',
    alias: 'Dr. Jorge Osorio',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín en funciones (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 6080,
    status: 'En funciones (Asumió curul en agosto 2026 en reemplazo de Claudia Carrasquilla)',
    bio: 'Médico cirujano, salubrista y académico de alto reconocimiento. Exrector de la Universidad CES. Asumió la curul en el Concejo de Medellín en agosto de 2026 tras la renuncia de la exfiscal Claudia Carrasquilla. Su labor legislativa enfoca la solvencia financiera de Metrosalud, hospitales públicos y educación superior.',
    extramunicipalConnection: 'Comité técnico nacional de salud del Centro Democrático, Asociación Colombiana de Facultades de Medicina (ASCOFAME).',
    municipalAnchor: 'Concejo de Medellín, Comisión de Asuntos Sociales y Salud, campus universitarios y red hospitalaria distrital.',
    socialProfiles: {
      xTwitter: '@JorgeOsorioCES',
      verifiedOfficial: false
    },
    newsLinks: [
      {
        title: 'El médico y exrector del CES Jorge Julián Osorio asume como concejal de Medellín',
        source: 'El Colombiano',
        year: 2026,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-luis-velez',
    name: 'Luis Guillermo Vélez Álvarez',
    alias: 'Luis Guillermo Vélez',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 14890,
    status: 'En funciones (Concejal)',
    bio: 'Economista y profesor universitario. Vocero técnico del Centro Democrático en temas presupuestales, finanzas de EPM y viabilidad fiscal.',
    extramunicipalConnection: 'Vínculo académico con centros de pensamiento del uribismo y gremios de Antioquia.',
    municipalAnchor: 'Concejo de Medellín, Comisión Segunda de Presupuesto.',
    socialProfiles: {
      xTwitter: '@LuisGVelez',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Luis Guillermo Vélez advierte sobre el déficit financiero de empresas públicas',
        source: 'Teleantioquia Noticias',
        year: 2024,
        sentiment: 'critico'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-andres-rodriguez',
    name: 'Andrés Rodríguez',
    alias: 'Gury Rodríguez',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 12110,
    status: 'En funciones (Concejal)',
    bio: 'Empresario y activista ciudadano. Lideró la revocatoria a Daniel Quintero. Representa el voto de opinión duro y confrontacional del Centro Democrático.',
    extramunicipalConnection: 'Coordinación con colectivos cívicos y veedurías de oposición a nivel nacional.',
    municipalAnchor: 'Concejo de Medellín y redes digitales de activismo de derecha.',
    socialProfiles: {
      xTwitter: '@GuryRodriguez',
      instagram: '@andresguryrodriguez',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Andrés Gury Rodríguez impulsa veedurías ciudadanas contra la corrupción',
        source: 'Revista Semana',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-leticia-orrego',
    name: 'Leticia Orrego Pérez',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático (Álvaro Uribe Vélez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 11450,
    status: 'En funciones (Concejal)',
    bio: 'Abogada con amplia trayectoria en derecho administrativo y control de gestión. Defensora de las familias populares y juntas de acción comunal.',
    extramunicipalConnection: 'Articulada con el Directorio Departamental del Centro Democrático en Antioquia.',
    municipalAnchor: 'Comunas nororientales y Comuna 13 (San Javier).',
    socialProfiles: {
      xTwitter: '@LeticiaOrregoP',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Leticia Orrego destaca inversión social comunitaria en Medellín',
        source: 'Minuto30',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-cd-concejal-bello-duvan-bedoya',
    name: 'Duván Alberto Bedoya García',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Bello',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 4590,
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Centro Democrático en Bello en las elecciones de 2023. Líder en fiscalización de contratación pública y desarrollo barrial en comunas de Bello.',
    extramunicipalConnection: 'Articulación con congresistas uribistas en la Cámara por Antioquia.',
    municipalAnchor: 'Concejo de Bello, comunas Niquía, Altos de Niquía y El Trapiche.',
    socialProfiles: { xTwitter: '@DuvanBedoyaBello', verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-bello-daniel-villa',
    name: 'Daniel Rodrigo Villa Maldonado',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Bello',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 3951,
    status: 'En funciones (Concejal)',
    bio: 'Segundo en votación del CD en Bello. Enfocado en seguridad comunitaria, gestión vial y apoyo a microempresarios locales.',
    extramunicipalConnection: 'Directorio Departamental del Centro Democrático.',
    municipalAnchor: 'Concejo de Bello, Comuna 4 (Suárez) y Comuna 5 (La Cumbre).',
    socialProfiles: { xTwitter: '@DanielVillaBello', verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-bello-jorge-arango',
    name: 'Jorge Armando Arango Palacio',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Bello',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 2604,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Bello con trabajo comunitario consolidado en el sector central y zonas industriales del norte.',
    extramunicipalConnection: 'Articulación con redes empresariales del Valle de Aburrá Norte.',
    municipalAnchor: 'Concejo de Bello y sector centro.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-itagui-walter-betancur',
    name: 'Walter Esneider Betancur Montoya',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Itagüí',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 8411,
    status: 'En funciones (Lista Cerrada CD)',
    bio: 'Cabeza de lista del Centro Democrático en Itagüí. Ejerce control político autónomo frente a la coalición hegemónica conservadora.',
    extramunicipalConnection: 'Articulación con Álvaro Uribe Vélez y senadores del Centro Democrático.',
    municipalAnchor: 'Concejo de Itagüí, comunas San Fernando y Ditaires.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-envigado-juan-uribe',
    name: 'Juan Fernando Uribe Restrepo',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 4120,
    status: 'En funciones (Concejal)',
    bio: 'Concejal del Centro Democrático en Envigado. Vocero de la bancada uribista en temas de ordenamiento territorial, finanzas y control ambiental.',
    extramunicipalConnection: 'Bancada del CD en la Asamblea de Antioquia y el Congreso.',
    municipalAnchor: 'Concejo de Envigado, zonas El Atravesado y Las Antillas.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-envigado-carlos-uribe',
    name: 'Carlos Manuel Uribe Mesa',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 3810,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Envigado con enfoque en fomento del emprendimiento, protección patrimonial y movilidad.',
    extramunicipalConnection: 'Redes gremiales del sur del Valle de Aburrá.',
    municipalAnchor: 'Concejo de Envigado y barrio San Marcos.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-envigado-jhony-velez',
    name: 'Jhony Oswaldo Vélez Quintero',
    alias: 'Jhony Vélez',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Oposición / CD)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 27702,
    status: 'En funciones (Curul Estatuto Oposición Ley 1909)',
    bio: 'Exdirector de Planeación y excandidato a la Alcaldía de Envigado en 2023 (segunda votación con más de 27.000 sufragios). Asumió curul de oposición bajo la Ley 1909.',
    extramunicipalConnection: 'Conexión directa con Álvaro Uribe Vélez y la jefatura del Centro Democrático.',
    municipalAnchor: 'Concejo de Envigado y coalición ciudadana de oposición en Envigado.',
    socialProfiles: { xTwitter: '@JhonyVelezEnv', verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-sabaneta-jose-restrepo',
    name: 'José Daniel Restrepo Montoya',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Sabaneta',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 2324,
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Centro Democrático en Sabaneta. Líder de debates sobre desarrollo urbano vertical, movilidad y espacio público.',
    extramunicipalConnection: 'Articulación con el Directorio Departamental de Antioquia.',
    municipalAnchor: 'Concejo de Sabaneta, veredas Las Lomitas y Cañaveralejo.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-sabaneta-julian-ceballos',
    name: 'Julián David Ceballos Montoya',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Sabaneta',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 764,
    status: 'En funciones (Concejal)',
    bio: 'Joven dirigente del Centro Democrático en Sabaneta. Trabaja en juventud, cultura y fomento del deporte barrial.',
    extramunicipalConnection: 'Red nacional de juventudes del Centro Democrático.',
    municipalAnchor: 'Concejo de Sabaneta y barrios centrales.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-copacabana-margarita-munoz',
    name: 'Margarita María Muñoz Giraldo',
    role: 'concejal',
    roleLabel: 'Concejal de Copacabana (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Copacabana',
    level: 4,
    sphere: 'municipal',
    municipality: 'Copacabana',
    department: 'Antioquia',
    votes2023: 377,
    cedula: '42.687.560',
    status: 'En funciones (Concejal)',
    bio: 'Concejal uribista en Copacabana. Defensora de las mujeres rurales y de las juntas de acción comunal.',
    extramunicipalConnection: 'Red de mujeres líderes del Centro Democrático en Antioquia.',
    municipalAnchor: 'Concejo de Copacabana y veredas del norte metropolitano.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-caldas-angela-espinosa',
    name: 'Angela María Espinosa Castro',
    role: 'concejal',
    roleLabel: 'Concejal de Caldas (Coalición CD - MIRA)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Caldas',
    level: 4,
    sphere: 'municipal',
    municipality: 'Caldas',
    department: 'Antioquia',
    votes2023: 732,
    cedula: '43.681.300',
    status: 'En funciones (Concejal)',
    bio: 'Concejal electa por la coalición Centro Democrático - Partido MIRA en el sur del Valle de Aburrá.',
    extramunicipalConnection: 'Articulación institucional con la bancada departamental en la Asamblea.',
    municipalAnchor: 'Concejo de Caldas y sector La Valeria.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-laestrella-willington-herrera',
    name: 'Willington Herrera Arroyave',
    role: 'concejal',
    roleLabel: 'Concejal de La Estrella (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / La Estrella',
    level: 4,
    sphere: 'municipal',
    municipality: 'La Estrella',
    department: 'Antioquia',
    votes2023: 533,
    cedula: '98.658.912',
    status: 'En funciones (Concejal)',
    bio: 'Concejal del Centro Democrático en La Estrella. Control político al presupuesto y vigilancia a licitaciones de infraestructura.',
    extramunicipalConnection: 'Directorio departamental del CD.',
    municipalAnchor: 'Concejo de La Estrella y sectores populares.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-laestrella-john-ocampo',
    name: 'John Edison Ocampo Mejía',
    role: 'concejal',
    roleLabel: 'Concejal de La Estrella (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / La Estrella',
    level: 4,
    sphere: 'municipal',
    municipality: 'La Estrella',
    department: 'Antioquia',
    votes2023: 380,
    cedula: '1.040.732.698',
    status: 'En funciones (Concejal)',
    bio: 'Líder social y concejal uribista en La Estrella. Enfocado en programas de juventud y empleo local.',
    extramunicipalConnection: 'Redes juveniles del uribismo en el sur metropolitano.',
    municipalAnchor: 'Concejo de La Estrella y barrio Ancón.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-barbosa-carlos-zapata',
    name: 'Carlos Andrés Zapata Chaverra',
    role: 'concejal',
    roleLabel: 'Concejal de Barbosa (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-centro-democratico-uribe',
    houseName: 'Casa Centro Democrático / Barbosa',
    level: 4,
    sphere: 'municipal',
    municipality: 'Barbosa',
    department: 'Antioquia',
    votes2023: 511,
    cedula: '1.035.233.703',
    status: 'En funciones (Concejal)',
    bio: 'Representante del Centro Democrático en el Concejo de Barbosa, extremo norte metropolitano. Líder en temas de vías veredales y defensa agropecuaria.',
    extramunicipalConnection: 'Articulación con comités del Norte de Antioquia y Gobernación.',
    municipalAnchor: 'Concejo de Barbosa y sector El Hatillo.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-rionegro-lina-ciro',
    name: 'Lina Marcela Ciro',
    role: 'concejal',
    roleLabel: 'Concejal de Rionegro (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-cd-oriente-rendon',
    houseName: 'Casa Centro Democrático / Paico - Uribe - Rendón',
    level: 4,
    sphere: 'municipal',
    municipality: 'Rionegro',
    department: 'Antioquia',
    votes2023: 2850,
    status: 'En funciones (Concejal)',
    bio: 'Líder del uribismo en Rionegro, bastión del Gobernador Andrés Julián Rendón y el senador Esteban Quintero. Coordinadora de la bancada del CD en el Oriente.',
    extramunicipalConnection: 'Enlace estrecho con el despacho del Gobernador Andrés Julián Rendón.',
    municipalAnchor: 'Concejo de Rionegro y sectores comerciales de San Antonio de Pereira.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-cd-concejal-rionegro-oscar-garcia',
    name: 'Oscar Johao García-Casarrubios',
    role: 'concejal',
    roleLabel: 'Concejal de Rionegro (Centro Democrático)',
    partyId: 'centro-democratico',
    partyName: 'Centro Democrático',
    houseId: 'casa-cd-oriente-rendon',
    houseName: 'Casa Centro Democrático / Paico - Uribe - Rendón',
    level: 4,
    sphere: 'municipal',
    municipality: 'Rionegro',
    department: 'Antioquia',
    votes2023: 2410,
    status: 'En funciones (Concejal)',
    bio: 'Concejal uribista en Rionegro. Impulsor del desarrollo agroindustrial y tecnológico del Oriente Antioqueño.',
    extramunicipalConnection: 'Articulación con la bancada del CD en la Cámara por Antioquia.',
    municipalAnchor: 'Concejo de Rionegro y veredas orientales.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },

  // --- CONCEJALES PARTIDO CREEMOS (MEDELLÍN Y METROPOLITANO) ---
  {
    id: 'actor-creemos-concejal-andres-tobon',
    name: 'Andrés Felipe Tobón Villada',
    alias: 'Andrés Tobón',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín - Más Votado (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 43795,
    cedula: '1.152.189.793',
    status: 'En funciones (Presidente Concejo 2024)',
    bio: 'Politólogo, exsecretario de Seguridad de Federico Gutiérrez. Fue la votación más alta al Concejo de Medellín en la historia de la ciudad.',
    extramunicipalConnection: 'Líder del comité de expansión nacional de Creemos y estratega clave de Fico.',
    municipalAnchor: 'Concejo de Medellín, redes comunitarias de seguridad y juventud.',
    socialProfiles: {
      xTwitter: '@tobonvillada',
      instagram: '@andrestobonv',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Andrés Tobón es elegido presidente del Concejo de Medellín con votación histórica',
        source: 'El Colombiano',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-creemos-concejal-paulina-suarez',
    name: 'María Paulina Suárez Roldán',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 16145,
    cedula: '43.597.417',
    status: 'En funciones (Concejal)',
    bio: 'Exsecretaria de Inclusión Social y Familia en el primer mandato de Fico. Especialista en infancia, adulto mayor y programas de nutrición.',
    extramunicipalConnection: 'Vínculo con fundaciones y organismos internacionales de desarrollo social.',
    municipalAnchor: 'Redes de madres comunitarias y programas de comedores en comunas populares.',
    socialProfiles: {
      xTwitter: '@suarezpaulina',
      instagram: '@mariapaulinasuarezr',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Paulina Suárez lidera política integral de atención a primera infancia en Medellín',
        source: 'Caracol Radio Medellín',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-creemos-concejal-santiago-perdomo',
    name: 'Santiago Perdomo Montoya',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 15240,
    cedula: '1.152.435.767',
    status: 'En funciones (Concejal)',
    bio: 'Líder juvenil de Creemos. Enfoque en innovación tecnológica, industrias creativas y empleo para jóvenes en el Valle del Software.',
    extramunicipalConnection: 'Articulación con ecosistemas de emprendimiento e innovación nacional.',
    municipalAnchor: 'Universidades de Medellín, Comuna 7 (Robledo) y Comuna 11 (Laureles).',
    socialProfiles: {
      xTwitter: '@SantiPerdomoM',
      instagram: '@santiagoperdomom',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Santiago Perdomo impulsa fondo distrital para becas de tecnología',
        source: 'Telemedellín',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-creemos-concejal-alejandro-bedout',
    name: 'Alejandro De Bedout Arango',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 11115,
    cedula: '10.376.006.12',
    status: 'En funciones (Concejal)',
    bio: 'Administrador de negocios, exsubsecretario de Creación y Fortalecimiento Empresarial. Enlace clave entre la bancada y los gremios de Fenalco y la ANDI.',
    extramunicipalConnection: 'Articulación con cámaras de comercio y gremios exportadores del país.',
    municipalAnchor: 'El Poblado, Laureles y corredores comerciales del centro de Medellín.',
    socialProfiles: {
      xTwitter: '@AlejoDeBedout',
      instagram: '@alejodebedout',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Alejandro De Bedout presenta plan de reactivación para comerciantes del centro',
        source: 'El Colombiano',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-creemos-concejal-juan-delacuesta',
    name: 'Juan Carlos De La Cuesta Galvis',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 9523,
    cedula: '71.741.348',
    status: 'En funciones (Concejal)',
    bio: 'Exitoso expresidente del Club Atlético Nacional (campeón de Copa Libertadores 2016). Dirige la agenda deportiva, recreativa y de grandes eventos internacionales en el Concejo.',
    extramunicipalConnection: 'Vínculos con federaciones deportivas nacionales y Conmebol.',
    municipalAnchor: 'Concejo de Medellín, INDER y sector deportivo distrital.',
    socialProfiles: { verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-damian-perez',
    name: 'Damián Pérez Arroyave',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 9338,
    cedula: '1.035.830.866',
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Medellín por Creemos. Enfoque en control a la contratación pública, transparencia y gobierno abierto.',
    extramunicipalConnection: 'Redes ciudadanas anticorrupción y veedurías.',
    municipalAnchor: 'Concejo de Medellín y comunas occidentales.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-envigado-luz-lopez',
    name: 'Luz Marina López Peña',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 2450,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Creemos en Envigado. Representa la expansión del movimiento de Federico Gutiérrez en el sur del Valle de Aburrá.',
    extramunicipalConnection: 'Articulación directa con el directorio metropolitano de Creemos.',
    municipalAnchor: 'Concejo de Envigado y sectores residenciales del sur.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-sabaneta-ivan',
    name: 'Iván Alonso Montoya Urrego',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Oposición / Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 13836,
    status: 'En funciones (Concejal Oposición Ley 1909)',
    bio: 'Exalcalde de Sabaneta (2016-2019). Obtuvo el segundo lugar para la Alcaldía en 2023 (13.836 votos) y asumió curul bajo el Estatuto de Oposición (Ley 1909).',
    extramunicipalConnection: 'Vínculo directo con Federico Gutiérrez y el comité metropolitano de Creemos.',
    municipalAnchor: 'Concejo de Sabaneta y barrios de Prados de Sabaneta y Calle Larga.',
    socialProfiles: {
      xTwitter: '@IvanMontoyaSaba',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Iván Montoya ejerce control estricto al plan de ordenamiento de Sabaneta',
        source: 'Periódico El Mundo',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  },
  {
    id: 'actor-creemos-concejal-sabaneta-alliday',
    name: 'Alliday Tobón Henao',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 850,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Creemos en Sabaneta. Defensora del medio ambiente, la cultura ciudadana y la inclusión comunitaria.',
    extramunicipalConnection: 'Comité de bancada metropolitana de Creemos.',
    municipalAnchor: 'Concejo de Sabaneta y sector Playas de María.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-copacabana-carlos-gomez',
    name: 'Carlos Alberto Gómez Yarce',
    role: 'concejal',
    roleLabel: 'Concejal de Copacabana (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Copacabana',
    department: 'Antioquia',
    votes2023: 1018,
    cedula: '1.035.425.982',
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado de Creemos en Copacabana. Respaldo clave para el alcalde Johnnatan Pineda en la corporación municipal.',
    extramunicipalConnection: 'Coordinación con el despacho del Alcalde de Medellín en temas de movilidad metropolitana.',
    municipalAnchor: 'Concejo de Copacabana y barrios de la zona urbana.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-copacabana-julian-tobon',
    name: 'Julián Andrés Tobón Martínez',
    role: 'concejal',
    roleLabel: 'Concejal de Copacabana (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Copacabana',
    department: 'Antioquia',
    votes2023: 647,
    cedula: '1.035.424.146',
    status: 'En funciones (Concejal)',
    bio: 'Concejal de la bancada de gobierno en Copacabana, impulsor de obras viales y saneamiento.',
    extramunicipalConnection: 'Área Metropolitana del Valle de Aburrá.',
    municipalAnchor: 'Concejo de Copacabana.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-caldas-luis-vergara',
    name: 'Luis Aníbal Vergara Ochoa',
    role: 'concejal',
    roleLabel: 'Concejal de Caldas (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Caldas',
    department: 'Antioquia',
    votes2023: 720,
    cedula: '71.394.549',
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Creemos en Caldas. Lidera iniciativas de protección a la cuenca alta del río Medellín y desarrollo comercial.',
    extramunicipalConnection: 'Articulación con directivas de Creemos Antioquia.',
    municipalAnchor: 'Concejo de Caldas y vereda La Miel.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-caldas-raul-mesa',
    name: 'Raúl Alejandro Mesa Correa',
    role: 'concejal',
    roleLabel: 'Concejal de Caldas (Oposición / Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Caldas',
    department: 'Antioquia',
    votes2023: 10982,
    cedula: '71.399.771',
    status: 'En funciones (Curul Oposición Ley 1909)',
    bio: 'Excandidato a la Alcaldía de Caldas con casi 11.000 votos en 2023. Asumió curul de oposición bajo la Ley 1909.',
    extramunicipalConnection: 'Vínculo directo con Federico Gutiérrez.',
    municipalAnchor: 'Concejo de Caldas y líderes comunitarios del sur.',
    socialProfiles: { verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-laestrella-fernando-moreno',
    name: 'Fernando de Jesús Moreno Moreno',
    role: 'concejal',
    roleLabel: 'Concejal de La Estrella (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'La Estrella',
    department: 'Antioquia',
    votes2023: 337,
    cedula: '7.158.322.1',
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Creemos en La Estrella. Enlace metropolitano en el sur.',
    extramunicipalConnection: 'Bancada metropolitana de Creemos.',
    municipalAnchor: 'Concejo de La Estrella.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-creemos-concejal-rionegro-victor-barreto',
    name: 'Víctor Alfonso Barreto',
    role: 'concejal',
    roleLabel: 'Concejal de Rionegro (Creemos)',
    partyId: 'creemos',
    partyName: 'Partido Político Creemos',
    houseId: 'casa-creemos-fico',
    houseName: 'Casa Creemos (Federico Gutiérrez)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Rionegro',
    department: 'Antioquia',
    votes2023: 2120,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Creemos en el Oriente Antioqueño. Vocero de la innovación y articulación empresarial en Rionegro.',
    extramunicipalConnection: 'Comité central de expansión regional de Creemos.',
    municipalAnchor: 'Concejo de Rionegro y sectores urbanos.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },

  // --- CONCEJALES PARTIDO CONSERVADOR (CASA TRUJILLO, SUÁREZ MIRA Y GERMÁN BLANCO) ---
  {
    id: 'actor-conservador-concejal-itagui-andres-arcila',
    name: 'Andrés Camilo Arcila Pérez',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Conservador - Equipo de Antioquia)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 3431,
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Partido Conservador en Itagüí en 2023. Uno de los alfiles más leales de la estructura de Carlos Andrés Trujillo.',
    extramunicipalConnection: 'Coordinación directa con el despacho del Senador Carlos Andrés Trujillo.',
    municipalAnchor: 'Concejo de Itagüí y Comuna 3.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-itagui-jorge-restrepo',
    name: 'Jorge Iván Restrepo Arias',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Conservador - Equipo de Antioquia)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 3392,
    status: 'En funciones (Concejal)',
    bio: 'Veterano dirigente conservador del Equipo de Antioquia. Miembro clave de la mesa directiva del Concejo de Itagüí.',
    extramunicipalConnection: 'Vínculos con la bancada conservadora en el Congreso.',
    municipalAnchor: 'Concejo de Itagüí y barrios San Pío y Calatrava.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-itagui-bayron-caro',
    name: 'Bayron de Jesús Caro Luján',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Conservador - Equipo de Antioquia)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 3064,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de amplia experiencia comunitaria en Itagüí, operador clave en la disciplina de votación del Equipo de Antioquia.',
    extramunicipalConnection: 'Estructura electoral departamental conservadora.',
    municipalAnchor: 'Concejo de Itagüí y Comuna 1.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-itagui-maria-gaviria',
    name: 'María Angélica Gaviria Londoño',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Conservador - Equipo de Antioquia)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 2647,
    status: 'En funciones (Concejal)',
    bio: 'Lideresa conservadora en Itagüí, defensora de programas sociales, equidad de género y adulto mayor.',
    extramunicipalConnection: 'Red de mujeres conservadoras de Colombia.',
    municipalAnchor: 'Concejo de Itagüí y juntas comunitarias.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-itagui-juan-martinez',
    name: 'Juan Pablo Martínez Cano',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Conservador - Equipo de Antioquia)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 2565,
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador de la bancada hegemónica de Itagüí. Sobresale en temas de seguridad y movilidad metropolitana.',
    extramunicipalConnection: 'Equipo de Antioquia en el sur del Valle de Aburrá.',
    municipalAnchor: 'Concejo de Itagüí y Ditaires.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-medellin-ramon-jimenez',
    name: 'Juan Ramón Jiménez Lara',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-blanco-conservadora',
    houseName: 'Casa Germán Blanco / Conservatismo Institucional',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 14500,
    cedula: '76.324.026',
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador más votado en Medellín. Reconocido activista por el bienestar animal, medio ambiente y políticas de protección ecológica.',
    extramunicipalConnection: 'Vínculo con el senador Germán Blanco y redes ambientalistas nacionales.',
    municipalAnchor: 'Concejo de Medellín, colectivos animalistas y ecologistas.',
    socialProfiles: { xTwitter: '@JuanRamonJimenezL', verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-medellin-brisvani-arenas',
    name: 'Brisvani Alexis Arenas Suaza',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 9657,
    cedula: '71.363.158',
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador de Medellín avalado con el respaldo del Equipo de Antioquia (Trujillo). Experto en planeación comunitaria y obras públicas.',
    extramunicipalConnection: 'Articulación directa con Carlos Andrés Trujillo y la bancada conservadora en el Congreso.',
    municipalAnchor: 'Concejo de Medellín y Comuna 5 (Castilla).',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-bello-gustavo-gomez',
    name: 'Gustavo Adolfo Gómez Suárez',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Partido Conservador - Suárez Mira)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-suarez-mira',
    houseName: 'Casa Suárez Mira (Bello)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 3410,
    status: 'En funciones (Concejal)',
    bio: 'Concejal del feudo conservador de Bello. Alfil de la alcaldesa Lorena González y de la histórica Casa Suárez Mira.',
    extramunicipalConnection: 'Articulación con Olga Suárez Mira y redes conservadoras del norte.',
    municipalAnchor: 'Concejo de Bello y sectores de Bello centro.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-envigado-gonzalo-mesa',
    name: 'Gonzalo de Jesús Mesa Ochoa',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-blanco-conservadora',
    houseName: 'Casa Germán Blanco / Conservatismo Institucional',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 3120,
    status: 'En funciones (Concejal)',
    bio: 'Veterano concejal conservador en Envigado. Baluarte del conservatismo tradicional en el sur metropolitano.',
    extramunicipalConnection: 'Directorio Departamental Conservador de Antioquia.',
    municipalAnchor: 'Concejo de Envigado y barrio Zuñiga.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-envigado-lucas-gaviria',
    name: 'Lucas Gaviria Henao',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-blanco-conservadora',
    houseName: 'Casa Germán Blanco / Conservatismo Institucional',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 2840,
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador con agenda de modernización institucional y desarrollo de infraestructura barrial en Envigado.',
    extramunicipalConnection: 'Redes conservadoras del sur metropolitano.',
    municipalAnchor: 'Concejo de Envigado.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-sabaneta-deifer',
    name: 'Deifer Alexander Morales Castaño',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 1592,
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador de Sabaneta afín a la red del Equipo de Antioquia.',
    extramunicipalConnection: 'Equipo de Antioquia en el sur del Valle de Aburrá.',
    municipalAnchor: 'Concejo de Sabaneta.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-caldas-sebastian-querubin',
    name: 'Sebastián Querubín Loaiza',
    role: 'concejal',
    roleLabel: 'Concejal de Caldas (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Caldas',
    department: 'Antioquia',
    votes2023: 553,
    cedula: '1.036.641.498',
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador en Caldas, clave en las votaciones de apoyo a proyectos de infraestructura regional.',
    extramunicipalConnection: 'Liderazgo conservador del sur metropolitano.',
    municipalAnchor: 'Concejo de Caldas.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-concejal-laestrella-camilo-cano',
    name: 'Andrés Camilo Cano Londoño',
    role: 'concejal',
    roleLabel: 'Concejal de La Estrella (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-trujillo',
    houseName: 'Casa Carlos Andrés Trujillo (Equipo de Antioquia)',
    level: 4,
    sphere: 'municipal',
    municipality: 'La Estrella',
    department: 'Antioquia',
    votes2023: 646,
    cedula: '1.040.737.013',
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservador de La Estrella, aliado de la administración local y del Equipo de Antioquia.',
    extramunicipalConnection: 'Casa Trujillo y Equipo de Antioquia.',
    municipalAnchor: 'Concejo de La Estrella y veredas bajas.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-conservador-girardota-berenice-alzate',
    name: 'María Berenice Álzate Castro',
    role: 'concejal',
    roleLabel: 'Concejal de Girardota (Partido Conservador)',
    partyId: 'conservador',
    partyName: 'Partido Conservador Colombiano',
    houseId: 'casa-suarez-mira',
    houseName: 'Casa Conservadora del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Girardota',
    department: 'Antioquia',
    votes2023: 1006,
    cedula: '39.353.402',
    status: 'En funciones (Concejal)',
    bio: 'Concejal conservadora más votada en Girardota. Defensora del patrimonio campesino y de las vías rurales.',
    extramunicipalConnection: 'Redes conservadoras del Norte y Valle de Aburrá.',
    municipalAnchor: 'Concejo de Girardota y veredas La Palma y San Andrés.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },

  // --- CONCEJALES PARTIDO LIBERAL (CASA LONDOÑO/ESPINOSA, BEDOYA Y ROLDÁN) ---
  {
    id: 'actor-liberal-concejal-envigado-pablo-restrepo',
    name: 'Pablo Andrés Restrepo Garcés',
    alias: 'Pablo Restrepo',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado - Más Votado (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-envigado-londono',
    houseName: 'Casa Héctor Londoño / Liberales de Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 5310,
    status: 'En funciones (Presidente Concejo Envigado)',
    bio: 'Concejal más votado del Partido Liberal en Envigado. Figura estelar de la hegemonía liberal envigadeña articulada con Braulio Espinosa y Héctor Londoño.',
    extramunicipalConnection: 'Articulación con congresistas liberales de Antioquia como Julián Peinado.',
    municipalAnchor: 'Concejo de Envigado, zonas El Dorado y San Marcos.',
    socialProfiles: { xTwitter: '@PabloRestrepoEnv', verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-envigado-david-londono',
    name: 'David Alfonso Londoño Arroyave',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-envigado-londono',
    houseName: 'Casa Héctor Londoño / Liberales de Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 4890,
    status: 'En funciones (Concejal)',
    bio: 'Miembro de la dinastía Londoño en Envigado. Defiende el modelo de gestión social y cobertura educativa del municipio.',
    extramunicipalConnection: 'Red de dirigentes liberales del sur del Valle de Aburrá.',
    municipalAnchor: 'Concejo de Envigado y zona centro.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-envigado-camilo-gomez',
    name: 'Camilo Andrés Gómez Mosquera',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-envigado-londono',
    houseName: 'Casa Héctor Londoño / Liberales de Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 4520,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de la bancada mayoritaria liberal de Envigado. Enfocado en medio ambiente urbano y deportes.',
    extramunicipalConnection: 'Directorio Liberal de Antioquia.',
    municipalAnchor: 'Concejo de Envigado.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-envigado-maria-alvarez',
    name: 'María Teresa Álvarez Muñoz',
    role: 'concejal',
    roleLabel: 'Concejal de Envigado (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-envigado-londono',
    houseName: 'Casa Héctor Londoño / Liberales de Envigado',
    level: 4,
    sphere: 'municipal',
    municipality: 'Envigado',
    department: 'Antioquia',
    votes2023: 4110,
    status: 'En funciones (Concejal)',
    bio: 'Lideresa de la bancada liberal en Envigado. Abogada con dedicación al fomento de la mujer y programas de salud preventiva.',
    extramunicipalConnection: 'Bancada de mujeres liberales en corporaciones públicas.',
    municipalAnchor: 'Concejo de Envigado.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-medellin-farley',
    name: 'Farley Jhair Macías Betancur',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 10491,
    cedula: '1.152.700.230',
    status: 'En funciones (Única Curul Liberal Medellín)',
    bio: 'Concejal de Medellín por el Partido Liberal Colombiano. Respaldo directo del senador John Jairo Roldán. Coordina la vocería del liberalismo en los debates presupuestales del Distrito.',
    extramunicipalConnection: 'Senador John Jairo Roldán y Dirección Nacional del Partido Liberal.',
    municipalAnchor: 'Concejo de Medellín, Comuna 2 (Santa Cruz) y Comuna 4 (Aranjuez).',
    socialProfiles: { xTwitter: '@FarleyMacias', verifiedOfficial: true },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-bello-carlos-mosquera',
    name: 'Carlos Augusto Mosquera Gómez',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 2529,
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Partido Liberal en Bello. Estructura territorial aliada al senador John Jairo Roldán.',
    extramunicipalConnection: 'Articulación legislativa con el Congreso Nacional.',
    municipalAnchor: 'Concejo de Bello y sector Niquía.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-bello-giovanni-giraldo',
    name: 'Giovanni Giraldo Jaramillo',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-bedoya-renovacion',
    houseName: 'Casa Julián Bedoya / Renovación Liberal',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 1922,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de la bancada liberal en Bello, vinculado a las redes de Renovación Liberal de Julián Bedoya.',
    extramunicipalConnection: 'Red política de Julián Bedoya y María Eugenia Lopera.',
    municipalAnchor: 'Concejo de Bello y Comuna 6 (Bellavista).',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-bello-luis-hernandez',
    name: 'Luis Carlos Hernández Giraldo',
    role: 'concejal',
    roleLabel: 'Concejal de Bello (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Bello',
    department: 'Antioquia',
    votes2023: 1899,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Bello por el Partido Liberal Colombiano. Líder en debates de equipamiento barrial y educación técnica.',
    extramunicipalConnection: 'Directorio Departamental Liberal.',
    municipalAnchor: 'Concejo de Bello.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-itagui-elkin-zuleta',
    name: 'Elkin de Jesús Zuleta Estrada',
    role: 'concejal',
    roleLabel: 'Concejal de Itagüí (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-bedoya-renovacion',
    houseName: 'Casa Julián Bedoya / Renovación Liberal',
    level: 4,
    sphere: 'municipal',
    municipality: 'Itagüí',
    department: 'Antioquia',
    votes2023: 2398,
    status: 'En funciones (Concejal)',
    bio: 'Único concejal liberal electo en Itagüí en 2023. Articulador de la bancada alternativa en el sur metropolitano.',
    extramunicipalConnection: 'Articulación con parlamentarios liberales de Antioquia.',
    municipalAnchor: 'Concejo de Itagüí y Comuna 4.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-sabaneta-fabricio',
    name: 'Ángel Fabricio Henao',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-prieto-liberal',
    houseName: 'Casa Eugenio Prieto / Liberales Institucionales',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 2514,
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Partido Liberal en Sabaneta. Líder de debates sobre movilidad y sostenibilidad fiscal en el sur.',
    extramunicipalConnection: 'Eugenio Prieto Soto y Secretaría de Hacienda Departamental.',
    municipalAnchor: 'Concejo de Sabaneta y sector céntrico.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-sabaneta-john-gonzalez',
    name: 'John Fredy González Montoya',
    role: 'concejal',
    roleLabel: 'Concejal de Sabaneta (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-envigado-londono',
    houseName: 'Casa Liberales del Sur',
    level: 4,
    sphere: 'municipal',
    municipality: 'Sabaneta',
    department: 'Antioquia',
    votes2023: 1609,
    status: 'En funciones (Concejal)',
    bio: 'Concejal de Sabaneta con amplia labor de fomento a clubes deportivos y microempresarios.',
    extramunicipalConnection: 'Redes liberales metropolitanas.',
    municipalAnchor: 'Concejo de Sabaneta.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-copacabana-julian-machado',
    name: 'Julián Marcelo Machado Cadavid',
    role: 'concejal',
    roleLabel: 'Concejal de Copacabana (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Copacabana',
    department: 'Antioquia',
    votes2023: 737,
    cedula: '15.515.272',
    status: 'En funciones (Concejal)',
    bio: 'Concejal del Partido Liberal en Copacabana, representante de las organizaciones comunitarias del norte.',
    extramunicipalConnection: 'Bancada liberal en la Asamblea de Antioquia.',
    municipalAnchor: 'Concejo de Copacabana.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-laestrella-juan-arteaga',
    name: 'Juan Pablo Arteaga Cano',
    role: 'concejal',
    roleLabel: 'Concejal de La Estrella (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-bedoya-renovacion',
    houseName: 'Casa Julián Bedoya / Renovación Liberal',
    level: 4,
    sphere: 'municipal',
    municipality: 'La Estrella',
    department: 'Antioquia',
    votes2023: 1242,
    cedula: '1.040.733.333',
    status: 'En funciones (Concejal)',
    bio: 'Concejal liberal más votado en La Estrella. Enlace territorial con redes hospitalarias y comunitarias del sur.',
    extramunicipalConnection: 'Estructura política de Julián Bedoya.',
    municipalAnchor: 'Concejo de La Estrella y sectores de La Tablaza.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-girardota-diego-congote',
    name: 'Diego Armando Congote Lopera',
    role: 'concejal',
    roleLabel: 'Concejal de Girardota (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Girardota',
    department: 'Antioquia',
    votes2023: 1184,
    cedula: '70.329.690',
    status: 'En funciones (Concejal)',
    bio: 'Concejal más votado del Partido Liberal en Girardota.',
    extramunicipalConnection: 'Liderazgo parlamentario liberal del Norte.',
    municipalAnchor: 'Concejo de Girardota.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },
  {
    id: 'actor-liberal-concejal-barbosa-mauricio-marin',
    name: 'Mauricio Antonio Marín Marín',
    role: 'concejal',
    roleLabel: 'Concejal de Barbosa (Partido Liberal)',
    partyId: 'liberal',
    partyName: 'Partido Liberal Colombiano',
    houseId: 'casa-roldan-norte',
    houseName: 'Casa John Jairo Roldán / Liberales del Norte',
    level: 4,
    sphere: 'municipal',
    municipality: 'Barbosa',
    department: 'Antioquia',
    votes2023: 600,
    cedula: '70.142.871',
    status: 'En funciones (Concejal)',
    bio: 'Concejal del Partido Liberal en Barbosa, enfocado en el desarrollo agrícola y transporte intermunicipal.',
    extramunicipalConnection: 'Directorio liberal departamental.',
    municipalAnchor: 'Concejo de Barbosa.',
    socialProfiles: { verifiedOfficial: false },
    newsLinks: []
  },

  // --- CONCEJALES PACTO HISTÓRICO / INDEPENDIENTES ---
  {
    id: 'actor-pacto-concejal-jose-marin',
    name: 'José Luis Marín',
    alias: 'Aquineto',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Pacto Histórico)',
    partyId: 'pacto-historico',
    partyName: 'Pacto Histórico',
    houseId: 'casa-pacto-independientes-quintero',
    houseName: 'Casa Pacto Histórico / Independientes (Daniel Quintero)',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 28410,
    status: 'En funciones (Concejal)',
    bio: 'Abogado y líder juvenil alternativo. Asumió la vocería de la oposición al gobierno distrital de Federico Gutiérrez en el Concejo de Medellín.',
    extramunicipalConnection: 'Vínculo estrecho con la bancada nacional del Pacto Histórico y el Gobierno Nacional.',
    municipalAnchor: 'Concejo de Medellín, colectivos estudiantiles y de derechos humanos.',
    socialProfiles: {
      xTwitter: '@Aquineto',
      instagram: '@aquinetomarin',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'José Luis Marín asume la curul de oposición del Pacto Histórico en Medellín',
        source: 'RCN Radio',
        year: 2024,
        sentiment: 'neutro'
      }
    ]
  },

  // --- CONCEJALES ALIANZA VERDE ---
  {
    id: 'actor-verde-concejal-camilo-londono',
    name: 'Camilo Londoño Rodríguez',
    role: 'concejal',
    roleLabel: 'Concejal de Medellín (Alianza Verde)',
    partyId: 'verde',
    partyName: 'Partido Alianza Verde',
    houseId: 'casa-creemos-gutierrez',
    houseName: 'Independientes / Centro Alternativo',
    level: 4,
    sphere: 'municipal',
    municipality: 'Medellín',
    department: 'Antioquia',
    votes2023: 13950,
    status: 'En funciones (Concejal)',
    bio: 'Ambientalista y urbanista. Vocero verde en el Concejo de Medellín con agenda centrada en sostenibilidad, movilidad limpia y protección de quebradas.',
    extramunicipalConnection: 'Articulado con congresistas verdes y el movimiento ambiental nacional.',
    municipalAnchor: 'Concejo de Medellín, colectivos ciclistas y redes ecologistas.',
    socialProfiles: {
      xTwitter: '@CamiloLondonoR',
      verifiedOfficial: true
    },
    newsLinks: [
      {
        title: 'Camilo Londoño lidera debate sobre calidad del aire y árboles urbanos en Medellín',
        source: 'Telemedellín',
        year: 2024,
        sentiment: 'positivo'
      }
    ]
  }
];"""

EDGES_REPLACEMENT = """  // Relevo de curules por renuncia en el Concejo de Medellín (Centro Democrático)
  {
    id: 'edge-cd-relevo-lopez-vasco',
    source: 'actor-lopez-sebastian',
    target: 'actor-cd-concejal-milton-vasco',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Relevo de Curul en Concejo (Mayo 2026)',
    description: 'Milton Darío Vasco Restrepo asumió la curul del Centro Democrático tras la renuncia de Sebastián López para liderar la campaña de Paloma Valencia.'
  },
  {
    id: 'edge-cd-relevo-carrasquilla-osorio',
    source: 'actor-cd-concejal-claudia-carrasquilla',
    target: 'actor-cd-concejal-jorge-osorio',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Relevo de Curul en Concejo (Agosto 2026)',
    description: 'Dr. Jorge Julián Osorio Gómez asumió la curul del Centro Democrático tras la renuncia de Claudia Carrasquilla para asumir como Viceministra de Defensa.'
  },
  {
    id: 'edge-uribe-vasco',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-milton-vasco',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Línea de Mando CD Medellín',
    description: 'Milton Vasco integra la bancada disciplinada del expresidente Álvaro Uribe en la corporación distrital.'
  },
  {
    id: 'edge-uribe-osorio',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-jorge-osorio',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Vocería Técnica y de Salud',
    description: 'Jorge Julián Osorio representa el ala académica y técnica del uribismo en el Concejo de Medellín.'
  },
  {
    id: 'edge-rendon-concejales-rionegro',
    source: 'actor-rendon-andres-julian',
    target: 'actor-cd-concejal-rionegro-lina-ciro',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Bastión del Gobernador en Oriente',
    description: 'Lina Marcela Ciro lidera la bancada leal a Andrés Julián Rendón en su feudo de Rionegro.'
  },
  {
    id: 'edge-rendon-concejales-rionegro-garcia',
    source: 'actor-rendon-andres-julian',
    target: 'actor-cd-concejal-rionegro-oscar-garcia',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Articulación Territorial CD Oriente',
    description: 'Oscar García respalda las prioridades de desarrollo vial del Gobernador Rendón en Rionegro.'
  },

  // Bancadas CD Valle de Aburrá
  {
    id: 'edge-uribe-cd-bello-duvan',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-bello-duvan-bedoya',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Bancada CD Bello',
    description: 'Duván Bedoya encabeza el bloque de concejales del Centro Democrático en Bello.'
  },
  {
    id: 'edge-uribe-cd-itagui-walter',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-itagui-walter-betancur',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Curul CD Itagüí',
    description: 'Walter Betancur representa la curul de opinión del Centro Democrático en el bastión conservador de Itagüí.'
  },
  {
    id: 'edge-uribe-cd-envigado-jhony',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-envigado-jhony-velez',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Liderazgo Oposición en Envigado',
    description: 'Jhony Vélez ejerce la vocería de más de 27.000 ciudadanos en el Concejo de Envigado.'
  },
  {
    id: 'edge-uribe-cd-sabaneta-restrepo',
    source: 'actor-uribe-alvaro',
    target: 'actor-cd-concejal-sabaneta-jose-restrepo',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Bancada CD Sabaneta',
    description: 'José Daniel Restrepo ejerce control a la densificación urbana en Sabaneta.'
  },

  // Conexiones Creemos
  {
    id: 'edge-fico-tobon',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-andres-tobon',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Fórmula de Gobierno / Presidente Concejo',
    description: 'Andrés Tobón es el principal alfil de Federico Gutiérrez en la corporación municipal de Medellín.'
  },
  {
    id: 'edge-fico-suarez',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-paulina-suarez',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Alfil Social de Bancada',
    description: 'Paulina Suárez canaliza las metas sociales del Plan de Desarrollo de Fico en el Concejo.'
  },
  {
    id: 'edge-fico-perdomo',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-santiago-perdomo',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Enlace Juvenil y Tecnológico',
    description: 'Santiago Perdomo lidera las iniciativas para jóvenes y emprendedores de Creemos.'
  },
  {
    id: 'edge-fico-bedout',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-alejandro-bedout',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Enlace Gremial y Empresarial',
    description: 'Alejandro De Bedout articula las relaciones del gobierno de Creemos con el sector privado.'
  },
  {
    id: 'edge-fico-delacuesta',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-juan-delacuesta',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Liderazgo Deportivo y Cívico',
    description: 'Juan Carlos De La Cuesta lidera los proyectos de infraestructura deportiva distrital.'
  },
  {
    id: 'edge-fico-sabaneta-montoya',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-sabaneta-ivan',
    type: 'alianza_electoral',
    strength: 5,
    label: 'Expansión de Creemos en Sabaneta',
    description: 'Iván Alonso Montoya defiende las banderas de Creemos en el sur del Valle de Aburrá.'
  },
  {
    id: 'edge-fico-copacabana-gomez',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-copacabana-carlos-gomez',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Bancada Creemos Copacabana',
    description: 'Carlos Alberto Gómez respalda al alcalde Johnnatan Pineda en Copacabana.'
  },
  {
    id: 'edge-fico-caldas-mesa',
    source: 'actor-gutierrez-federico',
    target: 'actor-creemos-concejal-caldas-raul-mesa',
    type: 'alianza_electoral',
    strength: 4,
    label: 'Líder Oposición en Caldas',
    description: 'Raúl Alejandro Mesa encabeza la oposición institucional de Creemos en Caldas.'
  },

  // Conexiones Conservador (Casa Trujillo y Casa Blanco)
  {
    id: 'edge-trujillo-concejales-itagui-arcila',
    source: 'actor-trujillo-carlos',
    target: 'actor-conservador-concejal-itagui-andres-arcila',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Control Hegemónico Equipo de Antioquia',
    description: 'Andrés Camilo Arcila responde con lealtad cerrada a las directrices de Trujillo en Itagüí.'
  },
  {
    id: 'edge-trujillo-concejales-itagui-restrepo',
    source: 'actor-trujillo-carlos',
    target: 'actor-conservador-concejal-itagui-jorge-restrepo',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Mesa Directiva Itagüí',
    description: 'Jorge Iván Restrepo coordina las iniciativas de gobierno en el Concejo de Itagüí.'
  },
  {
    id: 'edge-trujillo-concejales-medellin-arenas',
    source: 'actor-trujillo-carlos',
    target: 'actor-conservador-concejal-medellin-brisvani-arenas',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Curul de Trujillo en Medellín',
    description: 'Brisvani Arenas coordina la presencia del Equipo de Antioquia en la capital del departamento.'
  },
  {
    id: 'edge-blanco-concejales-medellin-jimenez',
    source: 'actor-blanco-conservadora',
    target: 'actor-conservador-concejal-medellin-ramon-jimenez',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Curul Conservatismo Institucional',
    description: 'Juan Ramón Jiménez articula la agenda ambiental con el senador Germán Blanco.'
  },
  {
    id: 'edge-suarez-concejales-bello-gomez',
    source: 'actor-gonzalez-lorena',
    target: 'actor-conservador-concejal-bello-gustavo-gomez',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Bancada de Gobierno en Bello',
    description: 'Gustavo Gómez apoya los proyectos estratégicos de la alcaldesa Lorena González.'
  },

  // Conexiones Liberal (Casa Londoño/Espinosa, Roldán y Bedoya)
  {
    id: 'edge-londono-concejales-envigado-restrepo',
    source: 'actor-londono-hector',
    target: 'actor-liberal-concejal-envigado-pablo-restrepo',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Hegemonía Liberal de Envigado',
    description: 'Pablo Restrepo preside la corporación y asegura la continuidad de los planes liberales.'
  },
  {
    id: 'edge-espinosa-concejales-envigado-david',
    source: 'actor-espinosa-braulio',
    target: 'actor-liberal-concejal-envigado-david-londono',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Gobernabilidad Liberal Envigado',
    description: 'David Londoño garantiza la disciplina de bancada del liberalismo en Envigado.'
  },
  {
    id: 'edge-roldan-concejal-medellin-farley',
    source: 'actor-roldan-norte',
    target: 'actor-liberal-concejal-medellin-farley',
    type: 'jerarquia_directa',
    strength: 5,
    label: 'Curul del Senador Roldán en Medellín',
    description: 'Farley Macías es el vocero exclusivo de la Casa John Jairo Roldán en el Concejo de Medellín.'
  },
  {
    id: 'edge-roldan-concejal-bello-mosquera',
    source: 'actor-roldan-norte',
    target: 'actor-liberal-concejal-bello-carlos-mosquera',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Bancada Liberal en Bello',
    description: 'Carlos Mosquera articula las bases liberales de Bello con el Congreso.'
  },
  {
    id: 'edge-bedoya-concejal-itagui-zuleta',
    source: 'actor-bedoya-julian',
    target: 'actor-liberal-concejal-itagui-elkin-zuleta',
    type: 'jerarquia_directa',
    strength: 4,
    label: 'Representación Liberal en Itagüí',
    description: 'Elkin Zuleta mantiene el enlace electoral con Renovación Liberal en el sur.'
  },

  // Conexiones Pacto Histórico
  {
    id: 'edge-quintero-marin',
    source: 'actor-quintero-daniel',
    target: 'actor-pacto-concejal-jose-marin',
    type: 'alianza_electoral',
    strength: 4,
    label: 'Articulación de Oposición en Medellín',
    description: 'José Luis Marín coordina la oposición distrital frente a la administración de Creemos.'
  }
];"""

def main():
    target_path = r"c:\Users\isaac\OneDrive\Documentos\Proyecto Proteus\src\data\politicalHouses\politicalHousesMasterData.ts"
    with open(target_path, "r", encoding="utf-8") as f:
        content = f.read().replace('\r\n', '\n')

    # 1. Reemplazar nodos de concejales
    start_nodes_marker = "// ==========================================\n  // CONCEJALES Y AGENTES MUNICIPALES POR PARTIDO (PA-009 EXTENDIDO)\n  // =========================================="
    end_nodes_marker = "export const GRAPH_EDGES_DATA: GraphEdgeRelation[] = ["

    idx_start_nodes = content.find(start_nodes_marker)
    if idx_start_nodes == -1:
        print("ERROR: no se encontró start_nodes_marker")
        sys.exit(1)

    idx_end_nodes = content.find(end_nodes_marker)
    if idx_end_nodes == -1:
        print("ERROR: no se encontró end_nodes_marker")
        sys.exit(1)

    # Buscamos el inicio de la línea donde está start_nodes_marker
    line_start_nodes = content.rfind('\n', 0, idx_start_nodes)
    if line_start_nodes == -1:
        line_start_nodes = 0
    else:
        line_start_nodes += 1

    new_content = content[:line_start_nodes] + NODES_REPLACEMENT + "\n\nexport const GRAPH_EDGES_DATA: GraphEdgeRelation[] = [\n"

    # Resto después de export const GRAPH_EDGES_DATA: GraphEdgeRelation[] = [
    rest_after_edges = content[idx_end_nodes + len(end_nodes_marker):]

    # En rest_after_edges, buscamos dónde empieza edge-cd-lopez-carrasquilla
    edge_marker = "id: 'edge-cd-lopez-carrasquilla'"
    idx_edge_marker = rest_after_edges.find(edge_marker)
    if idx_edge_marker == -1:
        print("ERROR: no se encontró edge_marker")
        sys.exit(1)

    # Buscamos el inicio del bloque { que contiene edge-cd-lopez-carrasquilla
    block_start = rest_after_edges.rfind('{\n', 0, idx_edge_marker)
    if block_start == -1:
        block_start = rest_after_edges.rfind('{', 0, idx_edge_marker)

    edges_before = rest_after_edges[:block_start]

    # Buscamos el final de GRAPH_EDGES_DATA
    end_edges_marker = "export const MASTER_POLITICAL_GRAPH: PoliticalGraphData = {"
    idx_end_edges = rest_after_edges.find(end_edges_marker)
    if idx_end_edges == -1:
        print("ERROR: no se encontró end_edges_marker")
        sys.exit(1)

    edges_closing = rest_after_edges.rfind('];', 0, idx_end_edges)
    after_edges = rest_after_edges[idx_end_edges:]

    final_content = (
        content[:line_start_nodes] + 
        NODES_REPLACEMENT + 
        "\n\nexport const GRAPH_EDGES_DATA: GraphEdgeRelation[] = [" + 
        edges_before + 
        EDGES_REPLACEMENT + 
        "\n\nexport const MASTER_POLITICAL_GRAPH: PoliticalGraphData = {" + 
        rest_after_edges[idx_end_edges + len(end_edges_marker):]
    )

    with open(target_path, "w", encoding="utf-8") as f:
        f.write(final_content)

    print("Archivo politicalHousesMasterData.ts actualizado con éxito.")

if __name__ == "__main__":
    main()
